"""Fetch every place in Türkiye by ILÇE (district) area, not by a box.

Why this replaces the bbox fetch
--------------------------------
fetch_demo_data.py fetches a bounding box per province. For the 19
hand-written cities that box is the metropolitan core; for the other 62 it
is a synthesized ~12 km x 12 km square around the provincial capital. A
data-quality audit measured what that actually covers: **2,2 % of
Türkiye's land area**. Antalya's file holds 1.668 places while the full
province holds 6.797 in six categories alone; Alanya (350.000 residents,
110 km from the box) has *nothing*, and the app meanwhile tells the user
"81 ilin 81 tanesi kapsanıyor". Only 16,8 % of the country's 973 district
centres had any data within 10 km.

The district is the right fetch unit for three separate reasons:

1. **Coverage.** 973 district areas tile the country exactly - no gaps
   between them, no overlap, no bbox guessing. Every settlement is inside
   exactly one.
2. **District labels for free.** Places came back from *this district's*
   area, so their district is known by construction. The tag-based path
   filled 6,7 % of records; there is nothing to infer and no polygon
   arithmetic to get wrong.
3. **Fewer requests, not more.** All 14 categories go in ONE union query
   per district: 973 requests, against the 1.134 (81 x 14) the province
   fetch needed. A district is small enough that one combined query is
   comfortable where a province-wide one would time out.

Output is unchanged: one places.<il>.json per province, same schema, so
nothing downstream has to know this script exists. Each place gains an
authoritative `district_raw` (and `province_raw`) from its fetch unit.

Checkpointed per district in .overpass-cache/districts/ - 973 requests
against a rate-limited free API will be interrupted, and losing 900 of
them to a 429 on the 901st is the failure this project has already
learned twice.

Usage:
    uv run --no-project python scripts/fetch_by_district.py
    uv run --no-project python scripts/fetch_by_district.py --province Antalya
    uv run --no-project python scripts/fetch_by_district.py --only-missing
"""

from __future__ import annotations

import argparse
import json
import sys
import time
import unicodedata
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # Windows cp1254 console

sys.path.insert(0, str(Path(__file__).resolve().parent))
from fetch_demo_data import (  # noqa: E402
    CATEGORIES,
    DATA_DIR,
    merge_multi_category,
    normalize,
    run_query,
)

ROOT = Path(__file__).resolve().parent.parent
DIVISIONS = ROOT / "frontend" / "data" / "admin-divisions.json"
CACHE_DIR = ROOT / ".overpass-cache" / "districts"

# One request per district, so the polite gap between them is what keeps the
# whole run under Overpass' fair-use ceiling. 6s x 973 is ~1.6 hours of pure
# waiting, which is the price of not being rate-limited into a backoff spiral.
POLITE_SLEEP_SECONDS = 6


def slugify(name: str) -> str:
    """Province name -> file slug, matching the existing places.<slug>.json
    names exactly (they were generated by the same rules)."""
    replacements = {
        "ı": "i", "İ": "i", "ğ": "g", "Ğ": "g", "ü": "u", "Ü": "u",
        "ş": "s", "Ş": "s", "ö": "o", "Ö": "o", "ç": "c", "Ç": "c",
        "â": "a", "Â": "a", "î": "i", "Î": "i", "û": "u", "Û": "u",
    }
    out = "".join(replacements.get(ch, ch) for ch in name)
    out = unicodedata.normalize("NFKD", out).encode("ascii", "ignore").decode()
    return out.lower().replace(" ", "").replace("-", "")


def district_query(area_id: int) -> str:
    """Every category in one union. `nwr` covers nodes, ways and relations -
    the bbox path used node+way only, so relation-mapped places (a park
    drawn as a multipolygon) were invisible to it."""
    parts = []
    for config in CATEGORIES.values():
        for selector in config["selectors"]:
            parts.append(f"  nwr{selector}(area:{area_id});")
    body = "\n".join(parts)
    return f"[out:json][timeout:300];\n(\n{body}\n);\nout center tags;"


def categories_for(element: dict) -> list[str]:
    """Which of our categories this OSM element satisfies.

    The bbox fetcher knew the category because it ran one query per
    category. A union query does not say which branch matched, so the
    selectors are re-evaluated here against the returned tags - and a place
    matching several stays one place with several categories, which is the
    data model's core promise.
    """
    tags = element.get("tags", {})
    matched = []
    for category, config in CATEGORIES.items():
        for selector in config["selectors"]:
            # Selectors are simple ["k"="v"] / ["k"!="v"] conjunctions.
            conditions = [c for c in selector.strip("[]").split("][") if c]
            ok = True
            for condition in conditions:
                if "!=" in condition:
                    key, value = condition.split("!=", 1)
                    if tags.get(key.strip('"')) == value.strip('"'):
                        ok = False
                        break
                else:
                    key, value = condition.split("=", 1)
                    if tags.get(key.strip('"')) != value.strip('"'):
                        ok = False
                        break
            if ok:
                matched.append(category)
                break
    return matched


def fetch_district(province: dict, district: dict) -> list[dict]:
    cache_dir = CACHE_DIR / slugify(province["name"])
    cache_dir.mkdir(parents=True, exist_ok=True)
    cache_file = cache_dir / f"{district['osm_relation']}.json"
    if cache_file.exists():
        return json.loads(cache_file.read_text(encoding="utf-8"))

    area_id = 3600000000 + district["osm_relation"]
    elements = run_query(district_query(area_id))

    places: list[dict] = []
    for element in elements:
        matched = categories_for(element)
        if not matched:
            continue
        # normalize() wants the category it was fetched under; the first
        # match names the place, merge_multi_category unions the rest.
        place = normalize(element, matched[0])
        if place is None:
            continue
        place["categories"] = sorted(set(matched))
        # Authoritative, because the query WAS this district's area. The
        # loader still prefers an explicit addr:* tag when OSM has one.
        place["district_raw"] = district["name"]
        place["province_raw"] = province["name"]
        places.append(place)

    cache_file.write_text(json.dumps(places, ensure_ascii=False), encoding="utf-8")
    return places


def write_province(province: dict, places: list[dict]) -> Path:
    slug = slugify(province["name"])
    merged = merge_multi_category(places)
    for place in merged:
        place["city"] = slug
    out_path = DATA_DIR / f"places.{slug}.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        json.dumps(
            {
                "city": slug,
                "city_label": province["name"],
                "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "source": "OpenStreetMap via Overpass API",
                "license": "ODbL 1.0",
                "attribution": "© OpenStreetMap katkıda bulunanları",
                # The unit this file was fetched by, so a reader never has to
                # guess whether it is a box or a boundary again.
                "fetch_unit": "district_areas",
                "district_count": len(province["districts"]),
                "count": len(merged),
                "places": merged,
            },
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )
    return out_path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--province", help="tek bir il (resmî adı)")
    parser.add_argument(
        "--only-missing",
        action="store_true",
        help="yalnızca henüz ilçe tabanlı çekilmemiş illeri işle",
    )
    args = parser.parse_args()

    data = json.loads(DIVISIONS.read_text(encoding="utf-8"))
    provinces = data["provinces"]
    if args.province:
        provinces = [p for p in provinces if p["name"] == args.province]
        if not provinces:
            raise SystemExit(f"il bulunamadı: {args.province}")

    total_places = 0
    for index, province in enumerate(provinces, 1):
        slug = slugify(province["name"])
        out_path = DATA_DIR / f"places.{slug}.json"
        if args.only_missing and out_path.exists():
            existing = json.loads(out_path.read_text(encoding="utf-8"))
            if existing.get("fetch_unit") == "district_areas":
                print(f"[{index:2}/{len(provinces)}] {province['name']}: zaten ilçe tabanlı, atlandı")
                continue

        print(f"\n=== [{index}/{len(provinces)}] {province['name']} "
              f"({len(province['districts'])} ilçe) ===")
        province_places: list[dict] = []
        for d_index, district in enumerate(province["districts"], 1):
            cached = (CACHE_DIR / slug / f"{district['osm_relation']}.json").exists()
            found = fetch_district(province, district)
            province_places.extend(found)
            print(f"  [{d_index:2}/{len(province['districts'])}] {district['name']:24} "
                  f"{len(found):5} mekan{' (önbellek)' if cached else ''}")
            if not cached:
                time.sleep(POLITE_SLEEP_SECONDS)

        path = write_province(province, province_places)
        merged_count = json.loads(path.read_text(encoding="utf-8"))["count"]
        total_places += merged_count
        print(f"  ✓ {province['name']}: {merged_count} mekan → {path.name}")

    print(f"\n✓ {len(provinces)} il işlendi, {total_places} mekan")


if __name__ == "__main__":
    main()
